# Generated by Django 5.1.1 on 2025-05-31 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_register'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='status',
        ),
    ]
